#!/bin/bash
# This script can be used to install Consul and its dependencies. This script has been tested with the following
# operating systems:
#
# - Ubuntu 16.04

set -e

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Include general-purpose bash functions from https://github.com/gruntwork-io/bash-commons. Assumes these were installed
# separately from this script, for example, using "cd /opt/gruntwork && git clone https://github.com/gruntwork-io/bash-commons".
source "/opt/gruntwork/bash-commons/assert.sh"
source "/opt/gruntwork/bash-commons/log.sh"

readonly DEFAULT_INSTALL_PATH="/opt/image-service"
readonly DEFAULT_CAT_USER="cat-image"
readonly SYSTEM_BIN_DIR="/usr/local/bin"

readonly SUPERVISOR_DIR="/etc/supervisor"
readonly SUPERVISOR_CONF_DIR="$SUPERVISOR_DIR/conf.d"

readonly SCRIPT_NAME="$(basename "$0")"

function print_usage {
  echo
  echo "Usage: install-image-service [OPTIONS]"
  echo
  echo "This script can be used to install Consul and its dependencies. This script has been tested with Ubuntu 16.04."
  echo
  echo "Required Arguments:"
  echo
  echo -e "  --version\t\tThe version of Consul to install. Do not include a \"v\" in the version number"
  echo
  echo "Optional Arguments:"
  echo
  echo -e "  --path\t\tThe path where Consul should be installed. Optional. Default: $DEFAULT_INSTALL_PATH."
  echo -e "  --user\t\tThe user who will own the Consul install directories. Optional. Default: $DEFAULT_CONSUL_USER."
  echo
  echo "Example:"
  echo
  echo "  install-consul --version 1.1.0"
}

# Install steps are based on: http://unix.stackexchange.com/a/291098/215969
function user_exists {
  local -r username="$1"
  id "$username" >/dev/null 2>&1
}

function create_image_service_user {
  local -r username="$1"

  if $(user_exists "$username"); then
    echo "User $username already exists. Will not create again."
  else
    log_info "Creating user named $username"
    sudo useradd --create-home "$username"
  fi
}

function install {
  local path="$DEFAULT_INSTALL_PATH"
  local user="$DEFAULT_CAT_USER"

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --path)
        path="$2"
        shift
        ;;
      --user)
        user="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_not_empty "--path" "$path"
  assert_not_empty "--user" "$user"

  log_info "Starting Image Service install"

  create_image_service_user "$user"

  log_info "Cat install complete!"
}

install "$@"
