# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skillitor/core/api/skillitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skillitor/core/api/skillitor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"skillitor/core/api/skillitor.proto\"L\n\nRawMessage\x12\x14\n\x0c\x63ommand_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ommand_text\x18\x02 \x01(\t\x12\x12\n\nuser_email\x18\x03 \x01(\t\"\x1b\n\x0bRawResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"B\n\x10SkillAssociation\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x1a\n\x06skills\x18\x02 \x03(\x0b\x32\n.SkillSpec\"?\n\x08\x46indSpec\x12\x13\n\x0b\x66ind_method\x18\x01 \x01(\t\x12\x1e\n\nskill_list\x18\x02 \x03(\x0b\x32\n.SkillSpec\"\x96\x01\n\tSkillSpec\x12\x12\n\nskill_name\x18\x01 \x01(\t\x12*\n\x0bskill_level\x18\x02 \x01(\x0e\x32\x15.SkillSpec.SkillLevel\"I\n\nSkillLevel\x12\r\n\tUNDEFINED\x10\x00\x12\x0c\n\x08\x42\x45GINNER\x10\x01\x12\x10\n\x0cINTERMEDIATE\x10\x02\x12\x0c\n\x08\x41\x44VANCED\x10\x03\"5\n\x0f\x41\x63knowledgement\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\terror_msg\x18\x02 \x01(\t\"\xba\x01\n\x0cRegistration\x12/\n\x0cservice_type\x18\x01 \x01(\x0e\x32\x19.Registration.ServiceType\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\"<\n\x0bServiceType\x12\r\n\tUNDEFINED\x10\x00\x12\x0f\n\x0bQUERY_AGENT\x10\x01\x12\r\n\tDATASTORE\x10\x02\x32\xcd\x01\n\x0eSkillitorQuery\x12\x30\n\tSetSkills\x12\x11.SkillAssociation\x1a\x10.Acknowledgement\x12\x32\n\x0bUnsetSkills\x12\x11.SkillAssociation\x1a\x10.Acknowledgement\x12,\n\nFindSkills\x12\t.FindSpec\x1a\x11.SkillAssociation0\x01\x12\'\n\nRawCommand\x12\x0b.RawMessage\x1a\x0c.RawResponse2A\n\x12SkillitorRegistrar\x12+\n\x08Register\x12\r.Registration\x1a\x10.Acknowledgementb\x06proto3')
)



_SKILLSPEC_SKILLLEVEL = _descriptor.EnumDescriptor(
  name='SkillLevel',
  full_name='SkillSpec.SkillLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BEGINNER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERMEDIATE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADVANCED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=356,
  serialized_end=429,
)
_sym_db.RegisterEnumDescriptor(_SKILLSPEC_SKILLLEVEL)

_REGISTRATION_SERVICETYPE = _descriptor.EnumDescriptor(
  name='ServiceType',
  full_name='Registration.ServiceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY_AGENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATASTORE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=613,
  serialized_end=673,
)
_sym_db.RegisterEnumDescriptor(_REGISTRATION_SERVICETYPE)


_RAWMESSAGE = _descriptor.Descriptor(
  name='RawMessage',
  full_name='RawMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_name', full_name='RawMessage.command_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command_text', full_name='RawMessage.command_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_email', full_name='RawMessage.user_email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=114,
)


_RAWRESPONSE = _descriptor.Descriptor(
  name='RawResponse',
  full_name='RawResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='RawResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=143,
)


_SKILLASSOCIATION = _descriptor.Descriptor(
  name='SkillAssociation',
  full_name='SkillAssociation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_email', full_name='SkillAssociation.user_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skills', full_name='SkillAssociation.skills', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=211,
)


_FINDSPEC = _descriptor.Descriptor(
  name='FindSpec',
  full_name='FindSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='find_method', full_name='FindSpec.find_method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_list', full_name='FindSpec.skill_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=276,
)


_SKILLSPEC = _descriptor.Descriptor(
  name='SkillSpec',
  full_name='SkillSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skill_name', full_name='SkillSpec.skill_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_level', full_name='SkillSpec.skill_level', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SKILLSPEC_SKILLLEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=429,
)


_ACKNOWLEDGEMENT = _descriptor.Descriptor(
  name='Acknowledgement',
  full_name='Acknowledgement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Acknowledgement.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='Acknowledgement.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=484,
)


_REGISTRATION = _descriptor.Descriptor(
  name='Registration',
  full_name='Registration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_type', full_name='Registration.service_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='Registration.service_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='access_token', full_name='Registration.access_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='Registration.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REGISTRATION_SERVICETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=673,
)

_SKILLASSOCIATION.fields_by_name['skills'].message_type = _SKILLSPEC
_FINDSPEC.fields_by_name['skill_list'].message_type = _SKILLSPEC
_SKILLSPEC.fields_by_name['skill_level'].enum_type = _SKILLSPEC_SKILLLEVEL
_SKILLSPEC_SKILLLEVEL.containing_type = _SKILLSPEC
_REGISTRATION.fields_by_name['service_type'].enum_type = _REGISTRATION_SERVICETYPE
_REGISTRATION_SERVICETYPE.containing_type = _REGISTRATION
DESCRIPTOR.message_types_by_name['RawMessage'] = _RAWMESSAGE
DESCRIPTOR.message_types_by_name['RawResponse'] = _RAWRESPONSE
DESCRIPTOR.message_types_by_name['SkillAssociation'] = _SKILLASSOCIATION
DESCRIPTOR.message_types_by_name['FindSpec'] = _FINDSPEC
DESCRIPTOR.message_types_by_name['SkillSpec'] = _SKILLSPEC
DESCRIPTOR.message_types_by_name['Acknowledgement'] = _ACKNOWLEDGEMENT
DESCRIPTOR.message_types_by_name['Registration'] = _REGISTRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RawMessage = _reflection.GeneratedProtocolMessageType('RawMessage', (_message.Message,), dict(
  DESCRIPTOR = _RAWMESSAGE,
  __module__ = 'skillitor.core.api.skillitor_pb2'
  # @@protoc_insertion_point(class_scope:RawMessage)
  ))
_sym_db.RegisterMessage(RawMessage)

RawResponse = _reflection.GeneratedProtocolMessageType('RawResponse', (_message.Message,), dict(
  DESCRIPTOR = _RAWRESPONSE,
  __module__ = 'skillitor.core.api.skillitor_pb2'
  # @@protoc_insertion_point(class_scope:RawResponse)
  ))
_sym_db.RegisterMessage(RawResponse)

SkillAssociation = _reflection.GeneratedProtocolMessageType('SkillAssociation', (_message.Message,), dict(
  DESCRIPTOR = _SKILLASSOCIATION,
  __module__ = 'skillitor.core.api.skillitor_pb2'
  # @@protoc_insertion_point(class_scope:SkillAssociation)
  ))
_sym_db.RegisterMessage(SkillAssociation)

FindSpec = _reflection.GeneratedProtocolMessageType('FindSpec', (_message.Message,), dict(
  DESCRIPTOR = _FINDSPEC,
  __module__ = 'skillitor.core.api.skillitor_pb2'
  # @@protoc_insertion_point(class_scope:FindSpec)
  ))
_sym_db.RegisterMessage(FindSpec)

SkillSpec = _reflection.GeneratedProtocolMessageType('SkillSpec', (_message.Message,), dict(
  DESCRIPTOR = _SKILLSPEC,
  __module__ = 'skillitor.core.api.skillitor_pb2'
  # @@protoc_insertion_point(class_scope:SkillSpec)
  ))
_sym_db.RegisterMessage(SkillSpec)

Acknowledgement = _reflection.GeneratedProtocolMessageType('Acknowledgement', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGEMENT,
  __module__ = 'skillitor.core.api.skillitor_pb2'
  # @@protoc_insertion_point(class_scope:Acknowledgement)
  ))
_sym_db.RegisterMessage(Acknowledgement)

Registration = _reflection.GeneratedProtocolMessageType('Registration', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATION,
  __module__ = 'skillitor.core.api.skillitor_pb2'
  # @@protoc_insertion_point(class_scope:Registration)
  ))
_sym_db.RegisterMessage(Registration)



_SKILLITORQUERY = _descriptor.ServiceDescriptor(
  name='SkillitorQuery',
  full_name='SkillitorQuery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=676,
  serialized_end=881,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetSkills',
    full_name='SkillitorQuery.SetSkills',
    index=0,
    containing_service=None,
    input_type=_SKILLASSOCIATION,
    output_type=_ACKNOWLEDGEMENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UnsetSkills',
    full_name='SkillitorQuery.UnsetSkills',
    index=1,
    containing_service=None,
    input_type=_SKILLASSOCIATION,
    output_type=_ACKNOWLEDGEMENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSkills',
    full_name='SkillitorQuery.FindSkills',
    index=2,
    containing_service=None,
    input_type=_FINDSPEC,
    output_type=_SKILLASSOCIATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RawCommand',
    full_name='SkillitorQuery.RawCommand',
    index=3,
    containing_service=None,
    input_type=_RAWMESSAGE,
    output_type=_RAWRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SKILLITORQUERY)

DESCRIPTOR.services_by_name['SkillitorQuery'] = _SKILLITORQUERY


_SKILLITORREGISTRAR = _descriptor.ServiceDescriptor(
  name='SkillitorRegistrar',
  full_name='SkillitorRegistrar',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=883,
  serialized_end=948,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='SkillitorRegistrar.Register',
    index=0,
    containing_service=None,
    input_type=_REGISTRATION,
    output_type=_ACKNOWLEDGEMENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SKILLITORREGISTRAR)

DESCRIPTOR.services_by_name['SkillitorRegistrar'] = _SKILLITORREGISTRAR

# @@protoc_insertion_point(module_scope)
