# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from skillitor.core.api import skillitor_pb2 as skillitor_dot_core_dot_api_dot_skillitor__pb2


class SkillitorQueryStub(object):
  """This query service should be accepted by both the core and datastore(s)
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetSkills = channel.unary_unary(
        '/SkillitorQuery/SetSkills',
        request_serializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.SkillAssociation.SerializeToString,
        response_deserializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.Acknowledgement.FromString,
        )
    self.UnsetSkills = channel.unary_unary(
        '/SkillitorQuery/UnsetSkills',
        request_serializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.SkillAssociation.SerializeToString,
        response_deserializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.Acknowledgement.FromString,
        )
    self.FindSkills = channel.unary_stream(
        '/SkillitorQuery/FindSkills',
        request_serializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.SkillList.SerializeToString,
        response_deserializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.SkillAssociation.FromString,
        )


class SkillitorQueryServicer(object):
  """This query service should be accepted by both the core and datastore(s)
  """

  def SetSkills(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnsetSkills(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindSkills(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SkillitorQueryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetSkills': grpc.unary_unary_rpc_method_handler(
          servicer.SetSkills,
          request_deserializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.SkillAssociation.FromString,
          response_serializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.Acknowledgement.SerializeToString,
      ),
      'UnsetSkills': grpc.unary_unary_rpc_method_handler(
          servicer.UnsetSkills,
          request_deserializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.SkillAssociation.FromString,
          response_serializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.Acknowledgement.SerializeToString,
      ),
      'FindSkills': grpc.unary_stream_rpc_method_handler(
          servicer.FindSkills,
          request_deserializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.SkillList.FromString,
          response_serializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.SkillAssociation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SkillitorQuery', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SkillitorRegistrarStub(object):
  """We need a way to register services to the core.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/SkillitorRegistrar/Register',
        request_serializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.Registration.SerializeToString,
        response_deserializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.Acknowledgement.FromString,
        )


class SkillitorRegistrarServicer(object):
  """We need a way to register services to the core.
  """

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SkillitorRegistrarServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.Registration.FromString,
          response_serializer=skillitor_dot_core_dot_api_dot_skillitor__pb2.Acknowledgement.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SkillitorRegistrar', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
