global:
  datacenter: dc1
  image: "consul:latest"
# Expose the Consul UI through this LoadBalancer
ui:
  service:
    type: "LoadBalancer"
# Allow Consul to inject the Connect proxy into Kubernetes containers
connectInject:
  enabled: true
# Configure a Consul client on Kubernetes nodes. GRPC listener is required for Connect.
client:
  enabled: true
  grpc: true
# Minimal Consul configuration. Not suitable for production.
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
# Sync Kubernetes and Consul services
syncCatalog:
  enabled: true
